### ISSUE TITLE
Pass context to the title, url and check. 

### ISSUE THREAD

**Issue by meizon** [borgstrom/django-simple-menu#35]
It would be useful to pass context to the functions such as title, url and check so that we can extract information from the context as well as the request. 

Something like:

check(request, context)

**Comment by borgstrom** [comment]
Hi.

Sorry, but this is a non-trivial change and I'm not going to attempt it.  If you feel it's something you think you can do cleanly I would consider a PR -- but it would require that no backwards compatible changes get introduced.

If you really need access to the context you can also always just reconstruct it in your callable:

    from django.template import RequestContext
    def my_check(request):
        context = RequestContext(request)

**Comment by meizon** [comment]
Yeah, I was probably going to look at attempting this in the not too distant future. I was going to check to see if the callable supports more than one argument as pass context as a secondary argument (to preserve backwards compatibility).

**Comment by borgstrom** [comment]
You'd probably need to do something like use `inspect.getargspec` to see if the callable supports a parameter named `context` and then supply it.
