### ISSUE TITLE
Check not behaving as expected

### ISSUE THREAD

**Issue by jordanbray** [borgstrom/django-simple-menu#39]
For some reason, the following menus don't seem to be displayed properly.  When the app is loaded (and no user is logged in), the "Log In" link is shown and the "Log Out" link is not shown (correctly).

When the user is logged in, *neither* link is shown.  (Originally, I blamed it on django-auth-ldap, but that doesn't seem to be the case, as there's no set of truth values which could cause this behavior.)

However, when I kill the server and restart it, Log Out is shown correctly.  If I then Log Out, then neither link is shown (again).  If I kill the server (again), then the Log In button is shown correctly.
 
I've tried both the 'master' branch from github and the latest verison in pip.

This could somehow still be either my fault or django-auth-ldap's fault, but it seems like the issue is here.

Thanks for looking over this report.

    menus.py                                                                                                                            
    from django.core.urlresolvers import reverse
    from menu import Menu, MenuItem

    children = (MenuItem("Log In",
                         reverse("auth.views.login"),
                         check=lambda request: request.user == None or (not request.user.is_authenticated())),
                MenuItem("Log Out",
                         reverse("auth.views.logout"),
                         check=lambda request: request.user != None and request.user.is_authenticated()),
               )

    Menu.add_item("main", MenuItem("Auth", reverse("auth.views.home"), children=children))

**Comment by jordanbray** [comment]
I tried this as well, and it doesn't seem like 'logged_in' and 'logged_out' are being called enough times.

    menus.py                                                                                                                            
    from django.core.urlresolvers import reverse
    from menu import Menu, MenuItem

    def logged_in(request):
        print("Logged In Called")
        if request.user == None:
            return False
        if request.user.is_authenticated():
            return True
        return False

    def logged_out(request):
        print("Logged Out Called")
        return not logged_in(request)

    children = (MenuItem("Log In",
                         reverse("auth.views.login"),
                         check=logged_out),
                MenuItem("Log Out",
                         reverse("auth.views.logout"),
                         check=logged_in),
               )

    Menu.add_item("main", MenuItem("Auth", reverse("auth.views.home"), children=children))

**Comment by borgstrom** [comment]
Hi @jordanbray,

Can you change the checks to the following and let me know if it behaves as you expect.

```
children = (MenuItem("Log In",
                     reverse("auth.views.login"),
                     check=lambda request: not request.user.is_authenticated()),
            MenuItem("Log Out",
                     reverse("auth.views.logout"),
                     check=lambda request: request.user.is_authenticated()),
           )
```

`request.user` should always be a User type object.

**Comment by borgstrom** [comment]
PS.  You can see these types of checks in the example:  https://github.com/borgstrom/django-simple-menu/blob/master/example/accounts/menus.py#L18

**Comment by borgstrom** [comment]
Closing this.  Please re-open if you feel there's still an issue.
