### ISSUE TITLE
Issues with internalization

### ISSUE THREAD

**Issue by desecho** [borgstrom/django-simple-menu#46]
Here's the code I had to use to make it work. What do you think about incorporating something of sorts in the module?

```python
class MenuItemTranslated(MenuItem):
    def __init__(self, name, url, reverse_kwargs=None, check=None, **kwargs):
        MenuItem.__init__(self, name, '', check=None, **kwargs)
        self.check = check
        self.url_ = url
        self.reverse_kwargs = reverse_kwargs

    def process(self, request):
        url = reverse(self.url_, kwargs=self.reverse_kwargs)
        self.url = url
        if callable(self.check):
            self.visible = self.check(request)```

**Comment by borgstrom** [comment]
Can you explain what problem you ran into that prompted you to write the above class?

How did you try to internationalize your menus and what errors did you face?

**Comment by desecho** [comment]
Please disregard. I guess it was a problem with an older version or something. It's working fine now.
